### ISSUE TITLE
The recipe tp-base-on-prem.yaml doesn't work on Docker Desktop for Windows

### ISSUE THREAD

**Issue by JurriaanBrandsmaTIBCO** [TIBCOSoftware/platform-provisioner#33]
The recipe tp-base-on-prem.yaml doesn't work on Docker Desktop for Windows, the installation of postgresql gets timed out. The issue seems to be related to the fact that Docker Desktop doesn't have a 'standard' storage class, it only has the storage class 'hostpath'. How can I solve this issue? Is there a way to set 'hostpath' as the storageclass name for the recipe?

Steps to reproduce
I ran the following commands:
curl -fsSL https://raw.githubusercontent.com/TIBCOSoftware/platform-provisioner/master/docs/recipes/tp-base/tp-base-on-prem.yaml -o tp-base-on-prem.yaml
export PIPELINE_NAME="helm-install"
export PIPELINE_INPUT_RECIPE="tp-base-on-prem.yaml"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/TIBCOSoftware/platform-provisioner/main/dev/platform-provisioner-pipelinerun.sh)"

The script provides the following logging. 

Skipping task 3 as task condition is: false
Skipping task 4 as task condition is: false
### [2024-11-24T18:59:09+0000][INFO]: helm upgrade --install -n tibco-ext --wait --timeout 1h --create-namespace postgresql postgresql-15.5.38.tgz --values values-current.yaml --values values-recipe.yaml  
Error: UPGRADE FAILED: client rate limiter Wait returned an error: context deadline exceeded
### [2024-11-24T20:06:57+0000][ERROR]: error: sub shell return none 0: 1

After an hour the script times out. 

I investigated the issue and found out the following:
1. I ran kubectl describe pod postgresql-0 -n tibco-ext. I think there is an issue with the PVC. It shows the error: "pod has unbound immediate PersistentVolumeClaims" (see full output below).
2. I ran kubectl describe pvc data-postgresql-0 -n tibco-ext. See output below. It seems the storage-class 'standard' is used.
3. The reason for the issue seems to be that in Docker Desktop doesn't have a 'standard' storage class. See the output of kubectl get storageclass below. Docker Desktop has a PVC named 'hostpath' only.

kubectl describe pod postgresql-0 -n tibco-ext  ==>
Name:             postgresql-0
Namespace:        tibco-ext
Priority:         0
Service Account:  postgresql
Node:             <none>
Labels:           app.kubernetes.io/component=primary
                  app.kubernetes.io/instance=postgresql
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=postgresql
                  app.kubernetes.io/version=16.4.0
                  apps.kubernetes.io/pod-index=0
                  controller-revision-hash=postgresql-5ddbcc4c5
                  helm.sh/chart=postgresql-15.5.38
                  statefulset.kubernetes.io/pod-name=postgresql-0
Annotations:      <none>
Status:           Pending
IP:
IPs:              <none>
Controlled By:    StatefulSet/postgresql
Containers:
  postgresql:
    Image:           docker.io/bitnami/postgresql:16.4.0-debian-12-r14
    Port:            5432/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    Limits:
      cpu:                150m
      ephemeral-storage:  2Gi
      memory:             192Mi
    Requests:
      cpu:                100m
      ephemeral-storage:  50Mi
      memory:             128Mi
    Liveness:             exec [/bin/sh -c exec pg_isready -U "postgres" -d "dbname=postgres" -h 127.0.0.1 -p 5432] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:            exec [/bin/sh -c -e exec pg_isready -U "postgres" -d "dbname=postgres" -h 127.0.0.1 -p 5432
[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                        false
      POSTGRESQL_PORT_NUMBER:               5432
      POSTGRESQL_VOLUME_DIR:                /bitnami/postgresql
      PGDATA:                               /bitnami/postgresql/data
      POSTGRES_PASSWORD:                    <set to the key 'postgres-password' in secret 'postgresql'>  Optional: false
      POSTGRES_DATABASE:                    postgres
      POSTGRESQL_ENABLE_LDAP:               no
      POSTGRESQL_ENABLE_TLS:                no
      POSTGRESQL_LOG_HOSTNAME:              false
      POSTGRESQL_LOG_CONNECTIONS:           false
      POSTGRESQL_LOG_DISCONNECTIONS:        false
      POSTGRESQL_PGAUDIT_LOG_CATALOG:       off
      POSTGRESQL_CLIENT_MIN_MESSAGES:       error
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES:  pgaudit
    Mounts:
      /bitnami/postgresql from data (rw)
      /dev/shm from dshm (rw)
      /opt/bitnami/postgresql/conf from empty-dir (rw,path="app-conf-dir")
      /opt/bitnami/postgresql/tmp from empty-dir (rw,path="app-tmp-dir")
      /tmp from empty-dir (rw,path="tmp-dir")
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-postgresql-0
    ReadOnly:   false
  empty-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  dshm:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      Memory
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  10s (x64 over 6h8m)  default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.

kubectl describe pvc data-postgresql-0 -n tibco-ext  ==>
Name:          data-postgresql-0
Namespace:     tibco-ext
StorageClass:  standard
Status:        Pending
Volume:
Labels:        app.kubernetes.io/component=primary
               app.kubernetes.io/instance=postgresql
               app.kubernetes.io/name=postgresql
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       postgresql-0
Events:
  Type     Reason              Age                    From                         Message
  ----     ------              ----                   ----                         -------
  Warning  ProvisioningFailed  73s (x229 over 6h21m)  persistentvolume-controller  storageclass.storage.k8s.io "standard" not found

kubectl get storageclass ==> 
NAME                 PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
hostpath (default)   docker.io/hostpath   Delete          Immediate           false                  7h33m

**Comment by syan-tibco** [comment]
Yeah the storage class is set either
```
meta.guiEvn.GUI_CP_STORAGE_CLASS: hostpath
```
or 
```
meta.globalEnvVariable.CP_STORAGE_CLASS: hostpath
```

You can also use the provisioner GUI to help to set. 

I see others already help you with the issue. will close the issue.
